/**
 * Pathway node and edge definitions for D3 rendering.
 * Each pathway has: nodes (metabolites + enzymes) and edges (reactions).
 */

export const PATHWAYS_DATA = {
  glycolysis: {
    id: "glycolysis",
    name: "Glycolysis",
    color: "#00ff88",
    nodes: [
      // metabolites (circle)
      { id: "glucose",    label: "Glucose",       type: "metabolite", x: 340, y: 40  },
      { id: "g6p",        label: "G6P",           type: "metabolite", x: 340, y: 120 },
      { id: "f6p",        label: "F6P",           type: "metabolite", x: 340, y: 200 },
      { id: "f16bp",      label: "F1,6BP",        type: "metabolite", x: 340, y: 280 },
      { id: "dhap_g3p",   label: "G3P × 2",       type: "metabolite", x: 340, y: 360 },
      { id: "bpg13",      label: "1,3-BPG",       type: "metabolite", x: 340, y: 430 },
      { id: "pg3",        label: "3-PG",          type: "metabolite", x: 340, y: 500 },
      { id: "pg2",        label: "2-PG",          type: "metabolite", x: 340, y: 570 },
      { id: "pep",        label: "PEP",           type: "metabolite", x: 340, y: 640 },
      { id: "pyruvate",   label: "Pyruvate",      type: "metabolite", x: 340, y: 720 },
      { id: "lactate",    label: "Lactate",       type: "metabolite", x: 520, y: 720 },
      { id: "acetyl_coa", label: "Acetyl-CoA",    type: "metabolite", x: 160, y: 720 },
      // enzymes (rectangle)
      { id: "HK",   label: "Hexokinase",       type: "enzyme", enzymeid: "HK",   x: 200, y: 80  },
      { id: "PGI",  label: "PGI",              type: "enzyme", enzymeid: "PGI",  x: 200, y: 160 },
      { id: "PFK1", label: "PFK-1 ★",          type: "enzyme", enzymeid: "PFK1", x: 200, y: 240 },
      { id: "ALD",  label: "Aldolase",         type: "enzyme", enzymeid: "ALD",  x: 200, y: 320 },
      { id: "GAPDH",label: "GAPDH",            type: "enzyme", enzymeid: "GAPDH",x: 200, y: 395 },
      { id: "PGK",  label: "PGK",              type: "enzyme", enzymeid: "PGK",  x: 200, y: 465 },
      { id: "PGM",  label: "PGM",              type: "enzyme", enzymeid: "PGM",  x: 200, y: 535 },
      { id: "ENO",  label: "Enolase",          type: "enzyme", enzymeid: "ENO",  x: 200, y: 605 },
      { id: "PK",   label: "Pyruvate Kinase ★",type: "enzyme", enzymeid: "PK",   x: 200, y: 680 },
      { id: "LDH",  label: "LDH",              type: "enzyme", enzymeid: "LDH",  x: 430, y: 680 },
      { id: "PDH",  label: "PDH Complex",      type: "enzyme", enzymeid: "PDH",  x: 90,  y: 680 },
    ],
    edges: [
      { source: "glucose",    target: "g6p",      enzyme: "HK"    },
      { source: "g6p",        target: "f6p",      enzyme: "PGI"   },
      { source: "f6p",        target: "f16bp",    enzyme: "PFK1"  },
      { source: "f16bp",      target: "dhap_g3p", enzyme: "ALD"   },
      { source: "dhap_g3p",   target: "bpg13",    enzyme: "GAPDH" },
      { source: "bpg13",      target: "pg3",      enzyme: "PGK"   },
      { source: "pg3",        target: "pg2",      enzyme: "PGM"   },
      { source: "pg2",        target: "pep",      enzyme: "ENO"   },
      { source: "pep",        target: "pyruvate", enzyme: "PK"    },
      { source: "pyruvate",   target: "lactate",  enzyme: "LDH"   },
      { source: "pyruvate",   target: "acetyl_coa",enzyme: "PDH"  },
    ],
  },

  tca_cycle: {
    id: "tca_cycle",
    name: "TCA Cycle",
    color: "#00d4ff",
    nodes: [
      { id: "acetyl_coa", label: "Acetyl-CoA",   type: "metabolite", x: 340, y: 30  },
      { id: "oaa",        label: "OAA",           type: "metabolite", x: 550, y: 130 },
      { id: "citrate",    label: "Citrate",       type: "metabolite", x: 620, y: 260 },
      { id: "isocitrate", label: "Isocitrate",    type: "metabolite", x: 580, y: 400 },
      { id: "akg",        label: "α-KG",          type: "metabolite", x: 460, y: 520 },
      { id: "succinyl",   label: "Succinyl-CoA",  type: "metabolite", x: 280, y: 520 },
      { id: "succinate",  label: "Succinate",     type: "metabolite", x: 130, y: 400 },
      { id: "fumarate",   label: "Fumarate",      type: "metabolite", x: 100, y: 260 },
      { id: "malate",     label: "Malate",        type: "metabolite", x: 200, y: 130 },
      { id: "CS",   label: "CS",   type: "enzyme", enzymeid: "CS",    x: 460, y: 80  },
      { id: "ACN",  label: "Aconitase",type:"enzyme",enzymeid:"ACN",  x: 630, y: 330 },
      { id: "IDH",  label: "IDH ★", type: "enzyme", enzymeid: "IDH", x: 550, y: 460 },
      { id: "AKGDH",label: "α-KGDH ★",type:"enzyme",enzymeid:"AKGDH",x:360, y: 520 },
      { id: "SCS",  label: "SCS",   type: "enzyme", enzymeid: "SCS", x: 200, y: 460 },
      { id: "SDH",  label: "SDH",   type: "enzyme", enzymeid: "SDH", x: 100, y: 330 },
      { id: "FUM",  label: "Fumarase",type:"enzyme",enzymeid:"FUM",   x: 130, y: 200 },
      { id: "MDH",  label: "MDH ★", type: "enzyme", enzymeid: "MDH", x: 310, y: 100 },
    ],
    edges: [
      { source: "acetyl_coa", target: "citrate",   enzyme: "CS"    },
      { source: "oaa",        target: "citrate",   enzyme: "CS"    },
      { source: "citrate",    target: "isocitrate",enzyme: "ACN"   },
      { source: "isocitrate", target: "akg",       enzyme: "IDH"   },
      { source: "akg",        target: "succinyl",  enzyme: "AKGDH" },
      { source: "succinyl",   target: "succinate", enzyme: "SCS"   },
      { source: "succinate",  target: "fumarate",  enzyme: "SDH"   },
      { source: "fumarate",   target: "malate",    enzyme: "FUM"   },
      { source: "malate",     target: "oaa",       enzyme: "MDH"   },
    ],
  },

  oxphos: {
    id: "oxphos",
    name: "Oxidative Phosphorylation",
    color: "#b388ff",
    nodes: [
      { id: "nadh",   label: "NADH",          type: "metabolite", x: 80,  y: 200 },
      { id: "fadh2",  label: "FADH₂",         type: "metabolite", x: 80,  y: 340 },
      { id: "ubiq",   label: "Ubiquinone (Q)", type: "metabolite", x: 340, y: 270 },
      { id: "cytc",   label: "Cytochrome c",   type: "metabolite", x: 520, y: 200 },
      { id: "h2o",    label: "H₂O",            type: "metabolite", x: 680, y: 200 },
      { id: "o2",     label: "O₂",             type: "metabolite", x: 680, y: 130 },
      { id: "pmf",    label: "Proton Gradient",type: "metabolite", x: 380, y: 430 },
      { id: "atp",    label: "ATP",            type: "metabolite", x: 540, y: 430 },
      { id: "adp",    label: "ADP + Pᵢ",       type: "metabolite", x: 210, y: 430 },
      { id: "CI",   label: "Complex I\nNADH-DH",  type: "enzyme", enzymeid: "CI",  x: 180, y: 200 },
      { id: "CII",  label: "Complex II\nSDH",      type: "enzyme", enzymeid: "CII", x: 180, y: 340 },
      { id: "CIII", label: "Complex III\nbc₁",     type: "enzyme", enzymeid: "CIII",x: 420, y: 200 },
      { id: "CIV",  label: "Complex IV\nCyt-c Ox", type: "enzyme", enzymeid: "CIV", x: 600, y: 200 },
      { id: "CV",   label: "Complex V\nATP Synthase",type:"enzyme",enzymeid:"CV",   x: 380, y: 430 },
    ],
    edges: [
      { source: "nadh",  target: "ubiq",  enzyme: "CI"   },
      { source: "fadh2", target: "ubiq",  enzyme: "CII"  },
      { source: "ubiq",  target: "cytc",  enzyme: "CIII" },
      { source: "cytc",  target: "h2o",   enzyme: "CIV"  },
      { source: "o2",    target: "h2o",   enzyme: "CIV"  },
      { source: "pmf",   target: "atp",   enzyme: "CV"   },
      { source: "adp",   target: "atp",   enzyme: "CV"   },
    ],
  },

  gluconeogenesis: {
    id: "gluconeogenesis",
    name: "Gluconeogenesis",
    color: "#ffaa00",
    nodes: [
      { id: "lactate_gng", label: "Lactate",      type: "metabolite", x: 340, y: 720 },
      { id: "pyruvate_gng",label: "Pyruvate",     type: "metabolite", x: 340, y: 640 },
      { id: "oaa_gng",     label: "OAA",          type: "metabolite", x: 340, y: 560 },
      { id: "pep_gng",     label: "PEP",          type: "metabolite", x: 340, y: 480 },
      { id: "f16bp_gng",   label: "F1,6BP",       type: "metabolite", x: 340, y: 320 },
      { id: "f6p_gng",     label: "F6P",          type: "metabolite", x: 340, y: 240 },
      { id: "g6p_gng",     label: "G6P",          type: "metabolite", x: 340, y: 160 },
      { id: "gng_glucose", label: "Glucose →",    type: "metabolite", x: 340, y: 80  },
      { id: "LDH_R", label: "LDH (rev.)", type: "enzyme", enzymeid: "LDH_R", x: 180, y: 680 },
      { id: "PC",    label: "Pyruvate\nCarboxylase ★",type:"enzyme",enzymeid:"PC",   x: 180, y: 600 },
      { id: "PEPCK", label: "PEPCK ★",   type: "enzyme", enzymeid: "PEPCK", x: 180, y: 520 },
      { id: "REV",   label: "Rev. Steps", type: "enzyme", enzymeid: "REV",  x: 180, y: 400 },
      { id: "FBP1",  label: "FBPase-1 ★",type: "enzyme", enzymeid: "FBP1", x: 180, y: 280 },
      { id: "PGI_R", label: "PGI (rev.)", type: "enzyme", enzymeid: "PGI_R",x: 180, y: 200 },
      { id: "G6PASE",label: "G6Pase",    type: "enzyme", enzymeid: "G6PASE",x:180,  y: 120 },
    ],
    edges: [
      { source: "lactate_gng",  target: "pyruvate_gng", enzyme: "LDH_R" },
      { source: "pyruvate_gng", target: "oaa_gng",      enzyme: "PC"    },
      { source: "oaa_gng",      target: "pep_gng",      enzyme: "PEPCK" },
      { source: "pep_gng",      target: "f16bp_gng",    enzyme: "REV"   },
      { source: "f16bp_gng",    target: "f6p_gng",      enzyme: "FBP1"  },
      { source: "f6p_gng",      target: "g6p_gng",      enzyme: "PGI_R" },
      { source: "g6p_gng",      target: "gng_glucose",  enzyme: "G6PASE"},
    ],
  },

  // ── Integrated: shows all 4 pathways in a single vertically-stacked map ──
  integrated: {
    id: "integrated",
    name: "Integrated Metabolism",
    color: "#00d4ff",
    nodes: [
      // ── Glycolysis block ──
      { id: "i_glucose",     label: "Glucose",        type: "metabolite", x: 380, y: 30  },
      { id: "i_g6p",         label: "G6P",            type: "metabolite", x: 380, y: 100 },
      { id: "i_f16bp",       label: "F1,6-BP",        type: "metabolite", x: 380, y: 170 },
      { id: "i_pyruvate",    label: "Pyruvate",       type: "metabolite", x: 380, y: 265 },
      { id: "i_lactate",     label: "Lactate",        type: "metabolite", x: 560, y: 265 },
      { id: "i_HK",    label: "HK",    type: "enzyme", enzymeid: "HK",    x: 230, y: 65  },
      { id: "i_PFK1",  label: "PFK-1 ★", type: "enzyme", enzymeid: "PFK1", x: 230, y: 135 },
      { id: "i_PK",    label: "PK ★",  type: "enzyme", enzymeid: "PK",    x: 230, y: 215 },
      { id: "i_LDH",   label: "LDH",   type: "enzyme", enzymeid: "LDH",   x: 470, y: 235 },

      // ── Acetyl-CoA junction ──
      { id: "i_acetyl",      label: "Acetyl-CoA",    type: "metabolite", x: 380, y: 340 },
      { id: "i_PDH",   label: "PDH",   type: "enzyme", enzymeid: "PDH",   x: 230, y: 300 },

      // ── TCA block ──
      { id: "i_citrate",     label: "Citrate",       type: "metabolite", x: 560, y: 400 },
      { id: "i_akg",         label: "α-KG",          type: "metabolite", x: 530, y: 480 },
      { id: "i_oaa",         label: "OAA",           type: "metabolite", x: 200, y: 400 },
      { id: "i_CS",    label: "CS",    type: "enzyme", enzymeid: "CS",    x: 460, y: 362 },
      { id: "i_IDH",   label: "IDH ★", type: "enzyme", enzymeid: "IDH",   x: 620, y: 440 },
      { id: "i_MDH",   label: "MDH",   type: "enzyme", enzymeid: "MDH",   x: 230, y: 440 },

      // ── OxPhos block ──
      { id: "i_nadh",        label: "NADH",          type: "metabolite", x: 200, y: 560 },
      { id: "i_atp_final",   label: "ATP",           type: "metabolite", x: 530, y: 580 },
      { id: "i_CI",    label: "CI",    type: "enzyme", enzymeid: "CI",    x: 300, y: 600 },
      { id: "i_CV",    label: "ATP Syn ★", type: "enzyme", enzymeid: "CV", x: 420, y: 620 },

      // ── GNG block (right side) ──
      { id: "i_gng_out",     label: "→ Glucose",     type: "metabolite", x: 680, y: 130 },
      { id: "i_PEPCK",       label: "PEPCK ★", type: "enzyme", enzymeid: "PEPCK", x: 680, y: 320 },
      { id: "i_G6PASE",      label: "G6Pase", type: "enzyme", enzymeid: "G6PASE", x: 680, y: 200 },
    ],
    edges: [
      { source: "i_glucose",  target: "i_g6p",      enzyme: "i_HK"    },
      { source: "i_g6p",      target: "i_f16bp",    enzyme: "i_PFK1"  },
      { source: "i_f16bp",    target: "i_pyruvate", enzyme: "i_PK"    },
      { source: "i_pyruvate", target: "i_lactate",  enzyme: "i_LDH"   },
      { source: "i_pyruvate", target: "i_acetyl",   enzyme: "i_PDH"   },
      { source: "i_acetyl",   target: "i_citrate",  enzyme: "i_CS"    },
      { source: "i_citrate",  target: "i_akg",      enzyme: "i_IDH"   },
      { source: "i_oaa",      target: "i_citrate",  enzyme: "i_CS"    },
      { source: "i_akg",      target: "i_oaa",      enzyme: "i_MDH"   },
      { source: "i_nadh",     target: "i_atp_final",enzyme: "i_CI"    },
      { source: "i_oaa",      target: "i_gng_out",  enzyme: "i_PEPCK" },
      { source: "i_gng_out",  target: "i_glucose",  enzyme: "i_G6PASE"},
    ],
  },

  // ── HMP Shunt / Pentose Phosphate Pathway ────────────────────────
  hmp_shunt: {
    id: "hmp_shunt",
    name: "HMP Shunt (Pentose Phosphate Pathway)",
    color: "#c084fc",
    nodes: [
      { id: "h_g6p",   label: "G6P",         type: "metabolite", x: 340, y: 40  },
      { id: "h_6pgl",  label: "6-PGL",        type: "metabolite", x: 340, y: 120 },
      { id: "h_6pg",   label: "6-PG",         type: "metabolite", x: 340, y: 200 },
      { id: "h_ru5p",  label: "Ru5P",         type: "metabolite", x: 340, y: 290 },
      { id: "h_r5p",   label: "R5P",          type: "metabolite", x: 185, y: 385 },
      { id: "h_x5p",   label: "X5P",          type: "metabolite", x: 500, y: 385 },
      { id: "h_s7p",   label: "S7P",          type: "metabolite", x: 200, y: 470 },
      { id: "h_e4p",   label: "E4P",          type: "metabolite", x: 480, y: 470 },
      { id: "h_f6p",   label: "F6P",          type: "metabolite", x: 280, y: 555 },
      { id: "h_g3p",   label: "G3P",          type: "metabolite", x: 400, y: 555 },
      { id: "h_nadph", label: "2 NADPH",      type: "metabolite", x: 525, y: 160 },
      { id: "G6PD",    label: "G6PD star",    type: "enzyme", enzymeid: "G6PD",  x: 195, y: 80  },
      { id: "LAC",     label: "Lactonase",    type: "enzyme", enzymeid: "LAC",   x: 195, y: 160 },
      { id: "h6PGD",   label: "6PGD",         type: "enzyme", enzymeid: "6PGD",  x: 195, y: 245 },
      { id: "RPI",     label: "RPI",          type: "enzyme", enzymeid: "RPI",   x: 240, y: 340 },
      { id: "RPE",     label: "RPE",          type: "enzyme", enzymeid: "RPE",   x: 445, y: 340 },
      { id: "TKT1",    label: "TKT (1)",      type: "enzyme", enzymeid: "TKT1",  x: 300, y: 428 },
      { id: "TALD",    label: "Transaldolase",type: "enzyme", enzymeid: "TALD",  x: 395, y: 428 },
      { id: "TKT2",    label: "TKT (2)",      type: "enzyme", enzymeid: "TKT2",  x: 340, y: 510 },
    ],
    edges: [
      { source: "h_g6p",  target: "h_6pgl",  enzyme: "G6PD"  },
      { source: "h_6pgl", target: "h_6pg",   enzyme: "LAC"   },
      { source: "h_6pg",  target: "h_ru5p",  enzyme: "h6PGD" },
      { source: "h_ru5p", target: "h_r5p",   enzyme: "RPI"   },
      { source: "h_ru5p", target: "h_x5p",   enzyme: "RPE"   },
      { source: "h_r5p",  target: "h_s7p",   enzyme: "TKT1"  },
      { source: "h_x5p",  target: "h_e4p",   enzyme: "TALD"  },
      { source: "h_s7p",  target: "h_f6p",   enzyme: "TALD"  },
      { source: "h_e4p",  target: "h_g3p",   enzyme: "TKT2"  },
      { source: "h_6pg",  target: "h_nadph", enzyme: "h6PGD" },
    ],
  },

  // ── Glycogenesis ─────────────────────────────────────────────────
  glycogenesis: {
    id: "glycogenesis",
    name: "Glycogenesis",
    color: "#00ff9d",
    nodes: [
      { id: "gs_glucose",  label: "Glucose",          type: "metabolite", x: 340, y: 40  },
      { id: "gs_g6p",      label: "G6P",              type: "metabolite", x: 340, y: 130 },
      { id: "gs_g1p",      label: "G1P",              type: "metabolite", x: 340, y: 220 },
      { id: "gs_udpglc",   label: "UDP-Glucose",      type: "metabolite", x: 340, y: 320 },
      { id: "gs_glycogen", label: "Glycogen(n+1)",    type: "metabolite", x: 340, y: 420 },
      { id: "gs_branch",   label: "Branched Glycogen",type: "metabolite", x: 340, y: 515 },
      { id: "gs_utp",      label: "UTP",              type: "metabolite", x: 525, y: 270 },
      { id: "gs_udp",      label: "UDP",              type: "metabolite", x: 525, y: 365 },
      { id: "HK2",   label: "HK/GK star",         type: "enzyme", enzymeid: "HK",   x: 190, y: 85  },
      { id: "PGMgs", label: "PGM",                 type: "enzyme", enzymeid: "PGM",  x: 190, y: 175 },
      { id: "UGPP",  label: "UGPPase",             type: "enzyme", enzymeid: "UGPP", x: 190, y: 270 },
      { id: "GSase", label: "Glycogen Synthase star",type:"enzyme", enzymeid: "GS",  x: 190, y: 370 },
      { id: "BE",    label: "Branching Enzyme",    type: "enzyme", enzymeid: "BE",   x: 190, y: 468 },
    ],
    edges: [
      { source: "gs_glucose",  target: "gs_g6p",      enzyme: "HK2"   },
      { source: "gs_g6p",      target: "gs_g1p",      enzyme: "PGMgs" },
      { source: "gs_utp",      target: "gs_udpglc",   enzyme: "UGPP"  },
      { source: "gs_g1p",      target: "gs_udpglc",   enzyme: "UGPP"  },
      { source: "gs_udpglc",   target: "gs_glycogen", enzyme: "GSase" },
      { source: "gs_udpglc",   target: "gs_udp",      enzyme: "GSase" },
      { source: "gs_glycogen", target: "gs_branch",   enzyme: "BE"    },
    ],
  },

  // ── Glycogenolysis ───────────────────────────────────────────────
  glycogenolysis: {
    id: "glycogenolysis",
    name: "Glycogenolysis",
    color: "#ff4d6d",
    nodes: [
      { id: "gl_glycogen",   label: "Glycogen",            type: "metabolite", x: 340, y: 40  },
      { id: "gl_g1p",        label: "G1P",                 type: "metabolite", x: 340, y: 160 },
      { id: "gl_g6p",        label: "G6P",                 type: "metabolite", x: 340, y: 270 },
      { id: "gl_glucose",    label: "Glucose (blood)",     type: "metabolite", x: 195, y: 385 },
      { id: "gl_glycolysis", label: "Glycolysis (muscle)", type: "metabolite", x: 485, y: 385 },
      { id: "gl_camp",       label: "cAMP",                type: "metabolite", x: 555, y: 80  },
      { id: "gl_amp",        label: "AMP (muscle)",        type: "metabolite", x: 130, y: 80  },
      { id: "GPA",   label: "GP-a star",            type: "enzyme", enzymeid: "GPA",   x: 185, y: 100 },
      { id: "PHKN",  label: "PhosphorylaseKinase",  type: "enzyme", enzymeid: "PHKN",  x: 455, y: 100 },
      { id: "DBE",   label: "Debranching Enzyme",   type: "enzyme", enzymeid: "DBE",   x: 528, y: 205 },
      { id: "PGM4",  label: "PGM",                  type: "enzyme", enzymeid: "PGM2",  x: 185, y: 215 },
      { id: "G6Pgl", label: "G6Pase (liver)",       type: "enzyme", enzymeid: "G6P",   x: 185, y: 330 },
    ],
    edges: [
      { source: "gl_camp",     target: "gl_glycogen",    enzyme: "PHKN"  },
      { source: "gl_amp",      target: "gl_glycogen",    enzyme: "GPA"   },
      { source: "gl_glycogen", target: "gl_g1p",         enzyme: "GPA"   },
      { source: "gl_glycogen", target: "gl_g1p",         enzyme: "DBE"   },
      { source: "gl_g1p",      target: "gl_g6p",         enzyme: "PGM4"  },
      { source: "gl_g6p",      target: "gl_glucose",     enzyme: "G6Pgl" },
      { source: "gl_g6p",      target: "gl_glycolysis",  enzyme: "G6Pgl" },
    ],
  },

  // ── Fructose Metabolism ──────────────────────────────────────────
  fructose_metabolism: {
    id: "fructose_metabolism",
    name: "Fructose Metabolism",
    color: "#ffb700",
    nodes: [
      { id: "fr_fructose", label: "Fructose",           type: "metabolite", x: 340, y: 40  },
      { id: "fr_f1p",      label: "F1P",                type: "metabolite", x: 340, y: 145 },
      { id: "fr_dhap",     label: "DHAP",               type: "metabolite", x: 195, y: 265 },
      { id: "fr_ga",       label: "Glyceraldehyde",     type: "metabolite", x: 485, y: 265 },
      { id: "fr_g3p",      label: "G3P",                type: "metabolite", x: 485, y: 375 },
      { id: "fr_pyruvate", label: "Pyruvate",           type: "metabolite", x: 340, y: 500 },
      { id: "fr_lactate",  label: "Lactate",            type: "metabolite", x: 510, y: 590 },
      { id: "fr_acetyl",   label: "Acetyl-CoA/Lipids",  type: "metabolite", x: 170, y: 590 },
      { id: "fr_uric",     label: "Uric Acid",          type: "metabolite", x: 555, y: 95  },
      { id: "KHK",   label: "Fructokinase star",  type: "enzyme", enzymeid: "KHK",   x: 185, y: 92  },
      { id: "ALDOB", label: "Aldolase B star",    type: "enzyme", enzymeid: "ALDOB", x: 185, y: 205 },
      { id: "TK",    label: "Triokinase",         type: "enzyme", enzymeid: "TK",    x: 510, y: 320 },
      { id: "GPDK",  label: "GAPDH to PK",        type: "enzyme", enzymeid: "GAPDH", x: 280, y: 445 },
    ],
    edges: [
      { source: "fr_fructose", target: "fr_f1p",      enzyme: "KHK"   },
      { source: "fr_fructose", target: "fr_uric",     enzyme: "KHK"   },
      { source: "fr_f1p",      target: "fr_dhap",     enzyme: "ALDOB" },
      { source: "fr_f1p",      target: "fr_ga",       enzyme: "ALDOB" },
      { source: "fr_ga",       target: "fr_g3p",      enzyme: "TK"    },
      { source: "fr_dhap",     target: "fr_pyruvate", enzyme: "GPDK"  },
      { source: "fr_g3p",      target: "fr_pyruvate", enzyme: "GPDK"  },
      { source: "fr_pyruvate", target: "fr_lactate",  enzyme: "GPDK"  },
      { source: "fr_pyruvate", target: "fr_acetyl",   enzyme: "GPDK"  },
    ],
  },

  // ── Galactose Metabolism (Leloir) ────────────────────────────────
  galactose_metabolism: {
    id: "galactose_metabolism",
    name: "Galactose Metabolism (Leloir)",
    color: "#2dd4bf",
    nodes: [
      { id: "gal_galactose", label: "Galactose",      type: "metabolite", x: 340, y: 40  },
      { id: "gal_gal1p",     label: "Gal-1-P",        type: "metabolite", x: 340, y: 145 },
      { id: "gal_udpgal",    label: "UDP-Galactose",  type: "metabolite", x: 530, y: 285 },
      { id: "gal_udpglc2",   label: "UDP-Glucose",    type: "metabolite", x: 530, y: 400 },
      { id: "gal_g1p",       label: "G1P",            type: "metabolite", x: 185, y: 285 },
      { id: "gal_g6p",       label: "G6P",            type: "metabolite", x: 185, y: 400 },
      { id: "gal_glycol",    label: "Glycolysis/Glycogenesis", type: "metabolite", x: 340, y: 515 },
      { id: "gal_galact",    label: "Galactitol(toxic)",type: "metabolite", x: 555, y: 92  },
      { id: "GALK",   label: "Galactokinase",     type: "enzyme", enzymeid: "GALK",  x: 185, y: 92  },
      { id: "GALT",   label: "GALT star",          type: "enzyme", enzymeid: "GALT",  x: 185, y: 215 },
      { id: "GALE",   label: "UDP-Gal Epimerase", type: "enzyme", enzymeid: "GALE",  x: 530, y: 345 },
      { id: "PGMgal", label: "PGM",               type: "enzyme", enzymeid: "PGM3",  x: 150, y: 345 },
    ],
    edges: [
      { source: "gal_galactose", target: "gal_gal1p",   enzyme: "GALK"   },
      { source: "gal_galactose", target: "gal_galact",   enzyme: "GALK"   },
      { source: "gal_gal1p",     target: "gal_g1p",     enzyme: "GALT"   },
      { source: "gal_gal1p",     target: "gal_udpgal",  enzyme: "GALT"   },
      { source: "gal_udpgal",    target: "gal_udpglc2", enzyme: "GALE"   },
      { source: "gal_udpglc2",   target: "gal_g1p",     enzyme: "GALT"   },
      { source: "gal_g1p",       target: "gal_g6p",     enzyme: "PGMgal" },
      { source: "gal_g6p",       target: "gal_glycol",  enzyme: "PGMgal" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // AMINO ACID METABOLISM
  // ═══════════════════════════════════════════════════════════════════

  amino_acid_catabolism: {
    id: 'amino_acid_catabolism',
    name: 'Amino Acid Catabolism',
    color: '#f472b6',
    nodes: [
      // Metabolites
      { id: 'ala',     label: 'Alanine',        type: 'metabolite', x: 200, y:  60 },
      { id: 'glu',     label: 'Glutamate',       type: 'metabolite', x: 390, y: 160 },
      { id: 'akg',     label: 'α-KG',            type: 'metabolite', x: 570, y: 280 },
      { id: 'oaa_aa',  label: 'OAA',             type: 'metabolite', x: 570, y: 160 },
      { id: 'pyr_aa',  label: 'Pyruvate',        type: 'metabolite', x: 200, y: 280 },
      { id: 'nh3',     label: 'NH₃',             type: 'metabolite', x: 390, y: 380 },
      { id: 'urea_m',  label: 'Urea',            type: 'metabolite', x: 390, y: 520 },
      // Enzymes
      { id: 'ALT',  label: 'ALT\n(Alanine-AT)',  type: 'enzyme', enzymeid: 'ALT',  x: 290, y: 120 },
      { id: 'AST',  label: 'AST\n(Asp-AT)',       type: 'enzyme', enzymeid: 'AST',  x: 490, y: 210 },
      { id: 'GDH',  label: 'GDH ★',              type: 'enzyme', enzymeid: 'GDH',  x: 390, y: 280 },
      { id: 'PDC',  label: 'PDH\nComplex',        type: 'enzyme', enzymeid: 'PDC',  x: 130, y: 380 },
      { id: 'PCC',  label: 'Propionyl-CoA\nCarboxylase', type: 'enzyme', enzymeid: 'PCC',  x: 390, y: 440 },
    ],
    edges: [
      { source: 'ala',    target: 'glu',    enzyme: 'ALT' },
      { source: 'ala',    target: 'pyr_aa', enzyme: 'ALT' },
      { source: 'oaa_aa', target: 'glu',    enzyme: 'AST' },
      { source: 'glu',    target: 'akg',    enzyme: 'GDH' },
      { source: 'glu',    target: 'nh3',    enzyme: 'GDH' },
      { source: 'pyr_aa', target: 'nh3',    enzyme: 'PDC' },
      { source: 'nh3',    target: 'urea_m', enzyme: 'PCC' },
    ],
  },

  urea_cycle: {
    id: 'urea_cycle',
    name: 'Urea Cycle',
    color: '#c084fc',
    nodes: [
      // Metabolites
      { id: 'nh3_uc',    label: 'NH₃',           type: 'metabolite', x: 200, y:  50 },
      { id: 'carp_uc',   label: 'Carbamoyl-P',   type: 'metabolite', x: 200, y: 160 },
      { id: 'citr_uc',   label: 'Citrulline',    type: 'metabolite', x: 200, y: 300 },
      { id: 'argsuc_uc', label: 'ArgSuccinate',  type: 'metabolite', x: 390, y: 420 },
      { id: 'arg_uc',    label: 'Arginine',      type: 'metabolite', x: 570, y: 300 },
      { id: 'orn_uc',    label: 'Ornithine',     type: 'metabolite', x: 570, y: 160 },
      { id: 'urea_uc',   label: 'Urea',          type: 'metabolite', x: 570, y:  50 },
      { id: 'fum_uc',    label: 'Fumarate\n→TCA', type: 'metabolite', x: 390, y: 550 },
      // Enzymes
      { id: 'CPS1', label: 'CPS-I ★',          type: 'enzyme', enzymeid: 'CPS1', x: 110, y: 110 },
      { id: 'OTC',  label: 'OTC',               type: 'enzyme', enzymeid: 'OTC',  x: 110, y: 230 },
      { id: 'ASS',  label: 'AS Synthetase',     type: 'enzyme', enzymeid: 'ASS',  x: 290, y: 370 },
      { id: 'ASL',  label: 'AS Lyase',          type: 'enzyme', enzymeid: 'ASL',  x: 490, y: 370 },
      { id: 'ARG1', label: 'Arginase-1',        type: 'enzyme', enzymeid: 'ARG1', x: 660, y: 230 },
    ],
    edges: [
      { source: 'nh3_uc',    target: 'carp_uc',   enzyme: 'CPS1' },
      { source: 'carp_uc',   target: 'citr_uc',   enzyme: 'OTC'  },
      { source: 'citr_uc',   target: 'argsuc_uc', enzyme: 'ASS'  },
      { source: 'argsuc_uc', target: 'arg_uc',    enzyme: 'ASL'  },
      { source: 'argsuc_uc', target: 'fum_uc',    enzyme: 'ASL'  },
      { source: 'arg_uc',    target: 'orn_uc',    enzyme: 'ARG1' },
      { source: 'arg_uc',    target: 'urea_uc',   enzyme: 'ARG1' },
      { source: 'orn_uc',    target: 'citr_uc',   enzyme: 'OTC'  },
    ],
  },

  phenylalanine_tyrosine: {
    id: 'phenylalanine_tyrosine',
    name: 'Phe/Tyr Metabolism',
    color: '#a78bfa',
    nodes: [
      { id: 'phe',     label: 'Phenylalanine',   type: 'metabolite', x: 200, y:  50 },
      { id: 'tyr',     label: 'Tyrosine',         type: 'metabolite', x: 200, y: 180 },
      { id: 'dopa',    label: 'L-DOPA',           type: 'metabolite', x: 390, y: 280 },
      { id: 'da',      label: 'Dopamine',         type: 'metabolite', x: 570, y: 320 },
      { id: 'na',      label: 'Noradrenaline',    type: 'metabolite', x: 690, y: 400 },
      { id: 'hga',     label: 'Homogentisate',    type: 'metabolite', x:  90, y: 380 },
      { id: 'fum_pt',  label: 'Fumarate',         type: 'metabolite', x:  90, y: 560 },
      { id: 'acac_pt', label: 'AcAcetate',        type: 'metabolite', x: 250, y: 560 },
      // Enzymes
      { id: 'PAH',  label: 'PAH ★\n(+BH4)',       type: 'enzyme', enzymeid: 'PAH',  x: 110, y: 115 },
      { id: 'TH',   label: 'Tyr-OH\n(Tyr→L-DOPA)',type: 'enzyme', enzymeid: 'TH',   x: 290, y: 230 },
      { id: 'AADC', label: 'AADC',                type: 'enzyme', enzymeid: 'AADC', x: 490, y: 300 },
      { id: 'DBH',  label: 'DBH',                 type: 'enzyme', enzymeid: 'DBH',  x: 640, y: 360 },
      { id: 'TAT',  label: 'TAT',                 type: 'enzyme', enzymeid: 'TAT',  x: 110, y: 270 },
      { id: 'HGD',  label: 'HGD',                 type: 'enzyme', enzymeid: 'HGD',  x: 110, y: 460 },
      { id: 'FAH',  label: 'FAH ★',               type: 'enzyme', enzymeid: 'FAH',  x: 170, y: 510 },
      { id: 'TYR',  label: 'Tyrosinase\n(Melanin)',type: 'enzyme', enzymeid: 'TYR',  x: 370, y: 150 },
    ],
    edges: [
      { source: 'phe',  target: 'tyr',     enzyme: 'PAH'  },
      { source: 'tyr',  target: 'dopa',    enzyme: 'TH'   },
      { source: 'dopa', target: 'da',      enzyme: 'AADC' },
      { source: 'da',   target: 'na',      enzyme: 'DBH'  },
      { source: 'tyr',  target: 'hga',     enzyme: 'TAT'  },
      { source: 'hga',  target: 'fum_pt',  enzyme: 'HGD'  },
      { source: 'hga',  target: 'acac_pt', enzyme: 'FAH'  },
    ],
  },

  branched_chain_aa: {
    id: 'branched_chain_aa',
    name: 'BCAA Catabolism',
    color: '#fb923c',
    nodes: [
      { id: 'bcaa_in',   label: 'Leu/Ile/Val',      type: 'metabolite', x: 200, y:  50 },
      { id: 'bcka',      label: 'Branched-chain\nKeto Acids', type: 'metabolite', x: 200, y: 200 },
      { id: 'ivcd',      label: 'Isovaleryl-CoA',   type: 'metabolite', x: 200, y: 370 },
      { id: 'acetcoa_b', label: 'Acetyl-CoA',       type: 'metabolite', x: 530, y: 500 },
      { id: 'succcoa_b', label: 'Succinyl-CoA',     type: 'metabolite', x: 200, y: 570 },
      { id: 'ketones_b', label: 'Ketones',           type: 'metabolite', x: 530, y: 350 },
      { id: 'mma_b',     label: 'MethylMalonate',   type: 'metabolite', x: 380, y: 620 },
      // Enzymes
      { id: 'BCAT2',    label: 'BCAT\n(mitoch.)',     type: 'enzyme', enzymeid: 'BCAT2',   x: 110, y: 130 },
      { id: 'BCKDH',    label: 'BCKDH ★\n(TPP,B1)',   type: 'enzyme', enzymeid: 'BCKDH',   x: 110, y: 290 },
      { id: 'IVD',      label: 'IVD\n(Leu branch)',   type: 'enzyme', enzymeid: 'IVD',     x: 110, y: 440 },
      { id: 'MCC',      label: 'MCC',                type: 'enzyme', enzymeid: 'MCC',     x: 380, y: 440 },
      { id: 'PCC_val',  label: 'PCC\n(→Succinyl-CoA)',type: 'enzyme', enzymeid: 'PCC_val', x: 300, y: 590 },
      { id: 'MUT',      label: 'MUT\n(B12)',          type: 'enzyme', enzymeid: 'MUT',     x: 450, y: 620 },
    ],
    edges: [
      { source: 'bcaa_in',   target: 'bcka',      enzyme: 'BCAT2'   },
      { source: 'bcka',      target: 'ivcd',      enzyme: 'BCKDH'   },
      { source: 'ivcd',      target: 'acetcoa_b', enzyme: 'IVD'     },
      { source: 'ivcd',      target: 'ketones_b', enzyme: 'MCC'     },
      { source: 'bcka',      target: 'succcoa_b', enzyme: 'PCC_val' },
      { source: 'succcoa_b', target: 'mma_b',     enzyme: 'MUT'     },
      { source: 'mma_b',     target: 'acetcoa_b', enzyme: 'MUT'     },
    ],
  },

  amino_acid_synthesis: {
    id: 'amino_acid_synthesis',
    name: 'Amino Acid Synthesis',
    color: '#34d399',
    nodes: [
      { id: 'akg_s',   label: 'α-Ketoglutarate',  type: 'metabolite', x: 390, y:  50 },
      { id: 'glu_s',   label: 'Glutamate',         type: 'metabolite', x: 390, y: 170 },
      { id: 'gln_s',   label: 'Glutamine',         type: 'metabolite', x: 570, y: 280 },
      { id: 'pro_s',   label: 'Proline',           type: 'metabolite', x: 570, y: 420 },
      { id: 'arg_s',   label: 'Arginine',          type: 'metabolite', x: 200, y: 420 },
      { id: 'oaa_s',   label: 'OAA',               type: 'metabolite', x: 200, y: 170 },
      { id: 'asp_s',   label: 'Aspartate',         type: 'metabolite', x: 200, y: 280 },
      { id: 'asn_s',   label: 'Asparagine',        type: 'metabolite', x:  80, y: 420 },
      // Enzymes
      { id: 'GDH_s',   label: 'GDH ★',             type: 'enzyme', enzymeid: 'GDH',  x: 390, y: 110 },
      { id: 'GS',      label: 'Gln Synthetase',    type: 'enzyme', enzymeid: 'GS',   x: 490, y: 225 },
      { id: 'P5CS',    label: 'P5CS',              type: 'enzyme', enzymeid: 'P5CS', x: 570, y: 350 },
      { id: 'AST_s',   label: 'AST',               type: 'enzyme', enzymeid: 'AST',  x: 290, y: 225 },
      { id: 'ASNS',    label: 'Asn Synthetase',    type: 'enzyme', enzymeid: 'ASN_SYN', x: 130, y: 350 },
    ],
    edges: [
      { source: 'akg_s', target: 'glu_s', enzyme: 'GDH_s' },
      { source: 'glu_s', target: 'gln_s', enzyme: 'GS'    },
      { source: 'glu_s', target: 'pro_s', enzyme: 'P5CS'  },
      { source: 'glu_s', target: 'arg_s', enzyme: 'P5CS'  },
      { source: 'oaa_s', target: 'asp_s', enzyme: 'AST_s' },
      { source: 'asp_s', target: 'asn_s', enzyme: 'ASNS'  },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // LIPID METABOLISM
  // ═══════════════════════════════════════════════════════════════════

  fatty_acid_oxidation: {
    id: 'fatty_acid_oxidation',
    name: 'β-Oxidation (FAO)',
    color: '#facc15',
    nodes: [
      { id: 'lcfa',      label: 'Long-Chain FA',     type: 'metabolite', x: 200, y:  50 },
      { id: 'malonyl',   label: 'Malonyl-CoA\n(CPT-I inhibitor)', type: 'metabolite', x: 450, y:  50 },
      { id: 'acyl_coa',  label: 'Acyl-CoA',          type: 'metabolite', x: 200, y: 200 },
      { id: 'acetcoa_f', label: 'Acetyl-CoA →TCA',   type: 'metabolite', x: 200, y: 620 },
      { id: 'fadh2_f',   label: 'FADH₂ →ETC',        type: 'metabolite', x: 530, y: 400 },
      { id: 'nadh_f',    label: 'NADH →ETC',         type: 'metabolite', x: 530, y: 500 },
      { id: 'ketone_f',  label: 'Ketones\n(starvation)', type: 'metabolite', x: 200, y: 490 },
      // Enzymes
      { id: 'CPT1',     label: 'CPT-I ★\n(rate-limiting)', type: 'enzyme', enzymeid: 'CPT1',     x: 110, y: 130 },
      { id: 'VLCAD',    label: 'VLCAD\n(C16-C20)',   type: 'enzyme', enzymeid: 'VLCAD',    x: 110, y: 270 },
      { id: 'MCAD',     label: 'MCAD ★\n(C8-C12)',   type: 'enzyme', enzymeid: 'MCAD',     x: 110, y: 370 },
      { id: 'LHAD',     label: 'L-HAD\n(→NADH)',     type: 'enzyme', enzymeid: 'LHAD',     x: 370, y: 450 },
      { id: 'THIOLASE', label: 'Thiolase',           type: 'enzyme', enzymeid: 'THIOLASE', x: 110, y: 540 },
    ],
    edges: [
      { source: 'lcfa',     target: 'acyl_coa',  enzyme: 'CPT1'     },
      { source: 'acyl_coa', target: 'acyl_coa',  enzyme: 'VLCAD'    },
      { source: 'acyl_coa', target: 'fadh2_f',   enzyme: 'VLCAD'    },
      { source: 'acyl_coa', target: 'fadh2_f',   enzyme: 'MCAD'     },
      { source: 'acyl_coa', target: 'nadh_f',    enzyme: 'LHAD'     },
      { source: 'acyl_coa', target: 'acetcoa_f', enzyme: 'THIOLASE' },
      { source: 'acyl_coa', target: 'ketone_f',  enzyme: 'THIOLASE' },
    ],
  },

  ketogenesis: {
    id: 'ketogenesis',
    name: 'Ketogenesis',
    color: '#f97316',
    nodes: [
      { id: 'acac',     label: 'Acetoacetate',   type: 'metabolite', x: 390, y: 100 },
      { id: 'bhb',      label: 'β-OHB',          type: 'metabolite', x: 390, y: 260 },
      { id: 'acetone',  label: 'Acetone',         type: 'metabolite', x: 600, y: 180 },
      { id: 'hmgcoa',   label: 'HMG-CoA\n(mito)', type: 'metabolite', x: 200, y: 180 },
      { id: 'acac_coa', label: 'AcAcetyl-CoA',   type: 'metabolite', x: 200, y:  50 },
      // Enzymes
      { id: 'HMGCS2', label: 'HMGCS2 ★\n(liver mito)',    type: 'enzyme', enzymeid: 'HMGCS2', x: 110, y: 115 },
      { id: 'HMGCL',  label: 'HMGCL\n(→AcAc)',            type: 'enzyme', enzymeid: 'HMGCL',  x: 290, y: 145 },
      { id: 'BDH1',   label: 'BDH1\n(AcAc↔β-OHB)',        type: 'enzyme', enzymeid: 'BDH1',   x: 390, y: 185 },
      { id: 'SCOT',   label: 'SCOT\n(absent in liver)',    type: 'enzyme', enzymeid: 'SCOT',   x: 530, y: 300 },
      { id: 'ACAT1',  label: 'ACAT1\n(ketolysis TCA)',     type: 'enzyme', enzymeid: 'ACAT1',  x: 530, y: 420 },
    ],
    edges: [
      { source: 'acac_coa', target: 'hmgcoa', enzyme: 'HMGCS2' },
      { source: 'hmgcoa',   target: 'acac',   enzyme: 'HMGCL'  },
      { source: 'acac',     target: 'bhb',    enzyme: 'BDH1'   },
      { source: 'acac',     target: 'acetone',enzyme: 'BDH1'   },
      { source: 'bhb',      target: 'acac',   enzyme: 'SCOT'   },
      { source: 'acac',     target: 'acac_coa',enzyme:'ACAT1'  },
    ],
  },

  fatty_acid_synthesis: {
    id: 'fatty_acid_synthesis',
    name: 'Fatty Acid Synthesis',
    color: '#4ade80',
    nodes: [
      { id: 'acetcoa_s', label: 'Acetyl-CoA\n(cytoplasm)', type: 'metabolite', x: 200, y:  60 },
      { id: 'malonyl_s', label: 'Malonyl-CoA',            type: 'metabolite', x: 390, y: 180 },
      { id: 'nadph_s',   label: 'NADPH\n(from G6PD/ME1)', type: 'metabolite', x: 600, y: 300 },
      { id: 'palm_s',    label: 'Palmitate\n(C16)',        type: 'metabolite', x: 390, y: 480 },
      { id: 'tg_s',      label: 'Triglycerides\n(storage)',type: 'metabolite', x: 390, y: 620 },
      // Enzymes
      { id: 'CLY',  label: 'ATP-Citrate\nLyase',      type: 'enzyme', enzymeid: 'CLY',  x: 110, y:  60 },
      { id: 'ACC1', label: 'ACC ★\n(rate-limiting)',   type: 'enzyme', enzymeid: 'ACC1', x: 290, y: 120 },
      { id: 'FASN', label: 'Fatty Acid\nSynthase',     type: 'enzyme', enzymeid: 'FASN', x: 390, y: 330 },
      { id: 'ME1',  label: 'Malic Enzyme\n(NADPH)',    type: 'enzyme', enzymeid: 'ME1',  x: 510, y: 180 },
    ],
    edges: [
      { source: 'acetcoa_s', target: 'acetcoa_s', enzyme: 'CLY'  },
      { source: 'acetcoa_s', target: 'malonyl_s', enzyme: 'ACC1' },
      { source: 'malonyl_s', target: 'palm_s',    enzyme: 'FASN' },
      { source: 'nadph_s',   target: 'palm_s',    enzyme: 'FASN' },
      { source: 'palm_s',    target: 'tg_s',      enzyme: 'FASN' },
    ],
  },

  cholesterol_synthesis: {
    id: 'cholesterol_synthesis',
    name: 'Cholesterol Synthesis',
    color: '#22d3ee',
    nodes: [
      { id: 'hmgcoa_c',  label: 'HMG-CoA\n(cyto)',    type: 'metabolite', x: 200, y:  50 },
      { id: 'meval_c',   label: 'Mevalonate',          type: 'metabolite', x: 200, y: 195 },
      { id: 'ipp_c',     label: 'Isopentenyl-PP',      type: 'metabolite', x: 200, y: 320 },
      { id: 'fpp_c',     label: 'Farnesyl-PP',         type: 'metabolite', x: 390, y: 420 },
      { id: 'squalene',  label: 'Squalene',            type: 'metabolite', x: 390, y: 530 },
      { id: 'chol_c',    label: 'Cholesterol',         type: 'metabolite', x: 390, y: 640 },
      { id: 'dolichol',  label: 'Dolichol\n(glyco-P)',type: 'metabolite', x: 580, y: 350 },
      { id: 'uq_c',      label: 'CoQ10\n(ETC)',        type: 'metabolite', x: 580, y: 470 },
      // Enzymes
      { id: 'HMGCR',  label: 'HMG-CoA\nReductase ★',   type: 'enzyme', enzymeid: 'HMGCR',  x: 110, y: 125 },
      { id: 'MVK',    label: 'Mevalonate\nKinase',       type: 'enzyme', enzymeid: 'MVK',    x: 110, y: 260 },
      { id: 'FPS',    label: 'FPP Synthase',             type: 'enzyme', enzymeid: 'FPS',    x: 290, y: 375 },
      { id: 'SQLE',   label: 'Squalene\nEpoxidase',     type: 'enzyme', enzymeid: 'SQLE',   x: 390, y: 480 },
      { id: 'DHCR7', label: 'DHCR7\n(SLO)',              type: 'enzyme', enzymeid: 'DHCR7',  x: 490, y: 590 },
    ],
    edges: [
      { source: 'hmgcoa_c', target: 'meval_c',  enzyme: 'HMGCR' },
      { source: 'meval_c',  target: 'ipp_c',    enzyme: 'MVK'   },
      { source: 'ipp_c',    target: 'fpp_c',    enzyme: 'FPS'   },
      { source: 'ipp_c',    target: 'dolichol', enzyme: 'FPS'   },
      { source: 'ipp_c',    target: 'uq_c',     enzyme: 'FPS'   },
      { source: 'fpp_c',    target: 'squalene', enzyme: 'SQLE'  },
      { source: 'squalene', target: 'chol_c',   enzyme: 'DHCR7' },
    ],
  },

  lipoprotein_metabolism: {
    id: 'lipoprotein_metabolism',
    name: 'Lipoprotein Metabolism',
    color: '#f87171',
    nodes: [
      { id: 'cm',     label: 'Chylomicron\n(gut)',       type: 'metabolite', x: 130, y:  60 },
      { id: 'vldl',   label: 'VLDL\n(liver)',            type: 'metabolite', x: 530, y:  60 },
      { id: 'ldl',    label: 'LDL',                      type: 'metabolite', x: 530, y: 280 },
      { id: 'hdl',    label: 'HDL\n(RCT)',               type: 'metabolite', x: 130, y: 480 },
      { id: 'cm_rem', label: 'Chylomicron\nRemnant',     type: 'metabolite', x: 130, y: 200 },
      { id: 'tg_pl',  label: 'Plasma TG\n(adipose)',     type: 'metabolite', x: 355, y: 150 },
      // Enzymes
      { id: 'LPL',   label: 'LPL ★\n(ApoC-II activ.)', type: 'enzyme', enzymeid: 'LPL',   x: 240, y: 130 },
      { id: 'LDLR',  label: 'LDL-R\n(hepatocyte)',      type: 'enzyme', enzymeid: 'LDLR',  x: 620, y: 180 },
      { id: 'PCSK9', label: 'PCSK9\n(degrades LDLR)',   type: 'enzyme', enzymeid: 'PCSK9', x: 690, y: 280 },
      { id: 'LCAT',  label: 'LCAT\n(ApoA-I activ.)',    type: 'enzyme', enzymeid: 'LCAT',  x: 130, y: 380 },
      { id: 'ABCA1', label: 'ABCA1\n(cholesterol efflux)',type:'enzyme', enzymeid: 'ABCA1', x: 130, y: 560 },
      { id: 'HTGL',  label: 'Hepatic TGL',              type: 'enzyme', enzymeid: 'HTGL',  x: 450, y: 350 },
    ],
    edges: [
      { source: 'cm',    target: 'cm_rem', enzyme: 'LPL'   },
      { source: 'cm',    target: 'tg_pl',  enzyme: 'LPL'   },
      { source: 'vldl',  target: 'ldl',    enzyme: 'HTGL'  },
      { source: 'vldl',  target: 'tg_pl',  enzyme: 'LPL'   },
      { source: 'ldl',   target: 'ldl',    enzyme: 'LDLR'  },
      { source: 'ldl',   target: 'ldl',    enzyme: 'PCSK9' },
      { source: 'hdl',   target: 'hdl',    enzyme: 'LCAT'  },
      { source: 'hdl',   target: 'hdl',    enzyme: 'ABCA1' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // NUCLEOTIDE METABOLISM
  // ═══════════════════════════════════════════════════════════════════

  purine_synthesis: {
    id: 'purine_synthesis',
    name: 'Purine Synthesis (De Novo)',
    color: '#67e8f9',
    nodes: [
      { id: 'prpp',   label: 'PRPP\n(R5P→)',      type: 'metabolite', x: 200, y:  50 },
      { id: 'imp',    label: 'IMP\n(branch pt)',   type: 'metabolite', x: 200, y: 280 },
      { id: 'amp_de', label: 'AMP →ATP',           type: 'metabolite', x:  80, y: 480 },
      { id: 'gmp_de', label: 'GMP →GTP',           type: 'metabolite', x: 340, y: 480 },
      { id: 'xmp',    label: 'XMP',                type: 'metabolite', x: 340, y: 360 },
      // Enzymes
      { id: 'PPAT',  label: 'PPAT ★\n(rate-lim.)',   type: 'enzyme', enzymeid: 'PPAT',  x: 110, y: 145 },
      { id: 'GART',  label: 'GART\n(steps 3+9)',     type: 'enzyme', enzymeid: 'GART',  x: 110, y: 220 },
      { id: 'IMPDH', label: 'IMPDH\n(→XMP→GMP)',    type: 'enzyme', enzymeid: 'IMPDH', x: 280, y: 320 },
      { id: 'ADSS',  label: 'ADSS\n(→AMP)',          type: 'enzyme', enzymeid: 'ADSS',  x:  80, y: 360 },
      { id: 'ADSL',  label: 'ADSL',                  type: 'enzyme', enzymeid: 'ADSL',  x:  80, y: 420 },
    ],
    edges: [
      { source: 'prpp',   target: 'imp',    enzyme: 'PPAT'  },
      { source: 'prpp',   target: 'imp',    enzyme: 'GART'  },
      { source: 'imp',    target: 'amp_de', enzyme: 'ADSS'  },
      { source: 'imp',    target: 'amp_de', enzyme: 'ADSL'  },
      { source: 'imp',    target: 'xmp',    enzyme: 'IMPDH' },
      { source: 'xmp',    target: 'gmp_de', enzyme: 'IMPDH' },
    ],
  },

  pyrimidine_synthesis: {
    id: 'pyrimidine_synthesis',
    name: 'Pyrimidine Synthesis',
    color: '#a3e635',
    nodes: [
      { id: 'carbasp',   label: 'Carbamoyl-Asp',    type: 'metabolite', x: 200, y:  60 },
      { id: 'dho',       label: 'Dihydroorotate',   type: 'metabolite', x: 200, y: 200 },
      { id: 'orotate',   label: 'Orotate',          type: 'metabolite', x: 200, y: 360 },
      { id: 'ump',       label: 'UMP',              type: 'metabolite', x: 200, y: 490 },
      { id: 'utp',       label: 'UTP →RNA',         type: 'metabolite', x:  80, y: 620 },
      { id: 'ctp',       label: 'CTP →RNA',         type: 'metabolite', x: 320, y: 620 },
      { id: 'dtmp',      label: 'dTMP →DNA',        type: 'metabolite', x: 540, y: 500 },
      { id: 'orotic_ac', label: 'Orotic Acid\n(urine)', type: 'metabolite', x: 430, y: 310 },
      // Enzymes
      { id: 'CAD',   label: 'CAD\n(CPS-II, mito)',  type: 'enzyme', enzymeid: 'CAD',   x: 110, y: 130 },
      { id: 'DHODH', label: 'DHODH ★\n(mito ETC)',  type: 'enzyme', enzymeid: 'DHODH', x: 110, y: 280 },
      { id: 'UMPS',  label: 'UMPS\n(OPRT+OMPDC)',   type: 'enzyme', enzymeid: 'UMPS',  x: 110, y: 425 },
      { id: 'CTPS1', label: 'CTP Synthase',         type: 'enzyme', enzymeid: 'CTPS1', x: 250, y: 555 },
      { id: 'TYMS',  label: 'TYMS ★\n(5-FU target)',type: 'enzyme', enzymeid: 'TYMS',  x: 440, y: 490 },
      { id: 'DHFR',  label: 'DHFR\n(MTX target)',   type: 'enzyme', enzymeid: 'DHFR',  x: 560, y: 395 },
    ],
    edges: [
      { source: 'carbasp', target: 'dho',       enzyme: 'CAD'   },
      { source: 'dho',     target: 'orotate',   enzyme: 'DHODH' },
      { source: 'orotate', target: 'orotic_ac', enzyme: 'DHODH' },
      { source: 'orotate', target: 'ump',       enzyme: 'UMPS'  },
      { source: 'ump',     target: 'utp',       enzyme: 'UMPS'  },
      { source: 'ump',     target: 'ctp',       enzyme: 'CTPS1' },
      { source: 'ump',     target: 'dtmp',      enzyme: 'TYMS'  },
      { source: 'dtmp',    target: 'dtmp',      enzyme: 'DHFR'  },
    ],
  },

  purine_salvage: {
    id: 'purine_salvage',
    name: 'Purine Salvage',
    color: '#818cf8',
    nodes: [
      { id: 'hx',     label: 'Hypoxanthine',   type: 'metabolite', x: 130, y:  60 },
      { id: 'gua',    label: 'Guanine',        type: 'metabolite', x: 470, y:  60 },
      { id: 'aden',   label: 'Adenine',        type: 'metabolite', x: 300, y:  60 },
      { id: 'adosn',  label: 'Adenosine',      type: 'metabolite', x: 300, y: 220 },
      { id: 'inosn',  label: 'Inosine',        type: 'metabolite', x: 130, y: 380 },
      { id: 'amp_sv', label: 'AMP →ATP',       type: 'metabolite', x: 530, y: 300 },
      { id: 'imp_sv', label: 'IMP',            type: 'metabolite', x: 130, y: 540 },
      // Enzymes
      { id: 'HGPRT', label: 'HGPRT ★\n(Lesch-Nyhan)', type: 'enzyme', enzymeid: 'HGPRT', x: 100, y: 180 },
      { id: 'APRT',  label: 'APRT\n(adenine salvage)', type: 'enzyme', enzymeid: 'APRT',  x: 420, y: 180 },
      { id: 'ADA',   label: 'ADA\n(SCID if defic.)',   type: 'enzyme', enzymeid: 'ADA',   x: 300, y: 310 },
      { id: 'AK',    label: 'Adenosine\nKinase',       type: 'enzyme', enzymeid: 'AK',    x: 430, y: 260 },
      { id: 'CD73',  label: 'CD73\n(ecto-5-NT)',        type: 'enzyme', enzymeid: 'CD73',  x: 200, y: 450 },
    ],
    edges: [
      { source: 'hx',    target: 'imp_sv', enzyme: 'HGPRT' },
      { source: 'gua',   target: 'imp_sv', enzyme: 'HGPRT' },
      { source: 'aden',  target: 'amp_sv', enzyme: 'APRT'  },
      { source: 'adosn', target: 'inosn',  enzyme: 'ADA'   },
      { source: 'adosn', target: 'amp_sv', enzyme: 'AK'    },
      { source: 'inosn', target: 'imp_sv', enzyme: 'CD73'  },
    ],
  },

  nucleotide_degradation: {
    id: 'nucleotide_degradation',
    name: 'Nucleotide Degradation',
    color: '#fb7185',
    nodes: [
      { id: 'adosn_d', label: 'Adenosine',        type: 'metabolite', x: 130, y:  50 },
      { id: 'inosn_d', label: 'Inosine',          type: 'metabolite', x: 130, y: 200 },
      { id: 'hx_d',    label: 'Hypoxanthine',     type: 'metabolite', x: 130, y: 360 },
      { id: 'xan_d',   label: 'Xanthine',         type: 'metabolite', x: 130, y: 500 },
      { id: 'ua',      label: 'Uric Acid\n(end product)', type: 'metabolite', x: 130, y: 640 },
      { id: 'ros_d',   label: 'H₂O₂ / ROS',      type: 'metabolite', x: 370, y: 500 },
      { id: 'bala_d',  label: 'β-Alanine\n(pyr catab.)', type: 'metabolite', x: 560, y: 350 },
      // Enzymes
      { id: 'ADA2',  label: 'ADA\n(Ado→Ino)',         type: 'enzyme', enzymeid: 'ADA2',  x:  50, y: 130 },
      { id: 'PNP',   label: 'PNP',                    type: 'enzyme', enzymeid: 'PNP',   x:  50, y: 280 },
      { id: 'XO',    label: 'Xanthine Oxidase ★\n(allopurinol target)', type: 'enzyme', enzymeid: 'XO', x: 50, y: 430 },
      { id: 'NT5E',  label: 'CD73 / 5-NT',            type: 'enzyme', enzymeid: 'NT5E',  x: 270, y: 130 },
      { id: 'DPYD',  label: 'DPYD\n(5-FU catabolism)', type: 'enzyme', enzymeid: 'DPYD', x: 460, y: 280 },
    ],
    edges: [
      { source: 'adosn_d', target: 'inosn_d', enzyme: 'ADA2' },
      { source: 'adosn_d', target: 'hx_d',    enzyme: 'NT5E' },
      { source: 'inosn_d', target: 'hx_d',    enzyme: 'PNP'  },
      { source: 'hx_d',    target: 'xan_d',   enzyme: 'XO'   },
      { source: 'xan_d',   target: 'ua',      enzyme: 'XO'   },
      { source: 'xan_d',   target: 'ros_d',   enzyme: 'XO'   },
      { source: 'bala_d',  target: 'bala_d',  enzyme: 'DPYD' },
    ],
  },
};
